// @generated by shiplightai v0.1.28
import { test, expect } from 'shiplightai/fixture';

test('Verify the inventory page displays products', async ({ page, agent }) => {
  // Test steps
  // main.0: Navigate to /inventory.html
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("go_to_url", page, {
      action_data: { kwargs: { url: "/inventory.html" } },
    });
  }, "Navigate to /inventory.html", 'main.0', '7192467c-688e-47fb-a902-fc10499472ce', true);

  // main.1: Verify: The inventory page is displayed with product listings
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.getByText('Products')).toBeVisible({ timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The inventory page is displayed with product listings"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The inventory page is displayed with product listings"`);
      await agent.assert(page, "The inventory page is displayed with product listings", "main.1");
    } }
  }, "Verify: The inventory page is displayed with product listings", 'main.1', '55ec2121-8c21-407b-b427-4a923a1e0955', false);

  // main.2: Click the first product name
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.locator('.inventory_item_name').first().click()
  }, "Click the first product name", 'main.2', 'c9ca6890-9a0a-4327-b2ac-9d08481e0e4b', true);

  // main.3: Verify: The product detail page is displayed
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.locator('.inventory_details_name')).toBeVisible({ timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The product detail page is displayed"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The product detail page is displayed"`);
      await agent.assert(page, "The product detail page is displayed", "main.3");
    } }
  }, "Verify: The product detail page is displayed", 'main.3', '329939ec-cb23-432f-8397-7053aa2aa5d6', false);
});