// @generated by shiplightai v0.1.28
import { test, expect } from 'shiplightai/fixture';

test('Verify inventory page elements', async ({ page, agent }) => {
  // Test steps
  // main.0: Navigate to /inventory.html
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("go_to_url", page, {
      action_data: { kwargs: { url: "/inventory.html" } },
    });
  }, "Navigate to /inventory.html", 'main.0', 'a8b9ef6f-f1a8-47e2-a1b1-f908b53cbb97', true);

  // main.1: Verify: The text 'Products' is visible as a heading on the page
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.getByText('Products')).toBeVisible({ timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The text 'Products' is visible as a heading on the page"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The text 'Products' is visible as a heading on the page"`);
      await agent.assert(page, "The text 'Products' is visible as a heading on the page", "main.1");
    } }
  }, "Verify: The text 'Products' is visible as a heading on the page", 'main.1', 'd588b8c0-898e-407f-b6f3-3712648d1552', false);

  // main.2: Verify: There are 6 product items displayed
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.locator('.inventory_item')).toHaveCount(6, { timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "There are 6 product items displayed"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "There are 6 product items displayed"`);
      await agent.assert(page, "There are 6 product items displayed", "main.2");
    } }
  }, "Verify: There are 6 product items displayed", 'main.2', '7d5682a4-be73-4572-8edf-6cbfd728a462', false);

  // main.3: Verify: The shopping cart icon is visible in the top right
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.locator('[data-test="shopping-cart-link"]')).toBeVisible({ timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The shopping cart icon is visible in the top right"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The shopping cart icon is visible in the top right"`);
      await agent.assert(page, "The shopping cart icon is visible in the top right", "main.3");
    } }
  }, "Verify: The shopping cart icon is visible in the top right", 'main.3', '8b3869c9-56e0-4c6f-8032-5008365b6ca8', false);

  // main.4: Verify: The sidebar menu button is visible
  page = agent.agentServices.validatePage(page);
  await agent.assert(page, "Verify: The sidebar menu button is visible", "main.4");

  // main.5: Verify: Each product has a name, description, price, and Add to cart button
  page = agent.agentServices.validatePage(page);
  await agent.assert(page, "Verify: Each product has a name, description, price, and Add to cart button", "main.5");
});