// @generated by shiplightai v0.1.28
import { test, expect } from 'shiplightai/fixture';

test('Add items to cart and verify using action entities', async ({ page, agent }) => {
  // Test steps
  // main.0: Navigate to /inventory.html
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("go_to_url", page, {
      action_data: { kwargs: { url: "/inventory.html" } },
    });
  }, "Navigate to /inventory.html", 'main.0', 'cac271dc-86e6-4def-93ed-14acd2e3d6d6', true);

  // main.1: Sort products by price low to high
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("select_dropdown_option", page, {
      action_data: { kwargs: { text: "Price (low to high)" } },
      locator: "getByRole('combobox')",
    });
  }, "Sort products by price low to high", 'main.1', 'fc3ff55a-4ce3-43a4-954c-e11f9658fdf3', true);

  // main.2: Verify: The first product has the lowest price
  page = agent.agentServices.validatePage(page);
  await agent.assert(page, "Verify: The first product has the lowest price", "main.2");

  // main.3: Add Sauce Labs Backpack to cart
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.locator('[data-test="add-to-cart-sauce-labs-backpack"]').first().click({ timeout: 5000 });
  }, "Add Sauce Labs Backpack to cart", 'main.3', 'a0782c93-02fc-41fe-927b-9b23fa834d48', true);

  // main.4: Add Sauce Labs Bike Light to cart
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.locator("xpath=//button[@id='add-to-cart-sauce-labs-bike-light']").first().click({ timeout: 5000 });
  }, "Add Sauce Labs Bike Light to cart", 'main.4', '47203408-4a98-4b64-a20d-a5f039ddd018', true);

  // main.5: Scroll down to see more products
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.evaluate('window.scrollBy(0, window.innerHeight * 1)');
  }, "Scroll down to see more products", 'main.5', '20b0ff6f-81e2-4a76-b8f2-332c7f54964e', true);

  // main.6: Scroll back up to top
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.evaluate('window.scrollBy(0, window.innerHeight * -1)');
  }, "Scroll back up to top", 'main.6', 'ac53bf09-1c34-45f1-bf0b-50976ea47f60', true);

  // main.7: Verify: The shopping cart badge shows the number 2
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.locator('[data-test="shopping-cart-badge"]')).toHaveText('2', { timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The shopping cart badge shows the number 2"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The shopping cart badge shows the number 2"`);
      await agent.assert(page, "The shopping cart badge shows the number 2", "main.7");
    } }
  }, "Verify: The shopping cart badge shows the number 2", 'main.7', 'ef0e2359-7101-46ae-b7c4-6da21319c20c', false);

  // main.8: Click the shopping cart icon
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.locator('[data-test="shopping-cart-link"]').click()
  }, "Click the shopping cart icon", 'main.8', '6e1ed37a-ce77-45ca-8974-d538555f7027', true);

  // main.9: Verify: Sauce Labs Backpack and Sauce Labs Bike Light are in the cart
  page = agent.agentServices.validatePage(page);
  await agent.assert(page, "Verify: Sauce Labs Backpack and Sauce Labs Bike Light are in the cart", "main.9");
});