// @generated by shiplightai v0.1.28
import { test, expect } from 'shiplightai/fixture';

test('Browse products with conditional logic', async ({ page, agent }) => {
  // Test steps
  // main.0: Navigate to /inventory.html
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("go_to_url", page, {
      action_data: { kwargs: { url: "/inventory.html" } },
    });
  }, "Navigate to /inventory.html", 'main.0', '75d5b757-0ef4-49ef-b127-ed8ffb753389', true);

  // Step: Add a product to the cart
  // main.1.0: Add Sauce Labs Backpack to cart
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.getByRole('button', { name: 'Add to cart' }).first().click()
  }, "Add Sauce Labs Backpack to cart", 'main.1.0', '3db411d7-03bd-4050-8b45-4ebba27cd013', true);

  // main.1.1: Verify: The shopping cart badge shows 1
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.locator('[data-test="shopping-cart-badge"]')).toHaveText('1', { timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The shopping cart badge shows 1"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The shopping cart badge shows 1"`);
      await agent.assert(page, "The shopping cart badge shows 1", "main.1.1");
    } }
  }, "Verify: The shopping cart badge shows 1", 'main.1.1', '220a42d0-a68b-4f98-b696-7d23a15c0b41', false);

  // main.2: Conditional check
  // AI Condition: The shopping cart badge shows a number greater than 0
  if (await agent.evaluate(page, "The shopping cart badge shows a number greater than 0", "main.2")) {
    // main.2.then.0: Click the shopping cart icon
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      await page.locator('[data-test="shopping-cart-link"]').click()
    }, "Click the shopping cart icon", 'main.2.then.0', 'a9150d44-28c2-4678-9695-f7f2b5dbdef4', true);

    // main.2.then.1: Verify: The cart page is displayed with items
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      { const _t = Date.now(); try {
        await expect(page.locator('.cart_item')).toHaveCount(1, { timeout: 2000 })
        console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The cart page is displayed with items"`);
      } catch (_e) {
        console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The cart page is displayed with items"`);
        await agent.assert(page, "The cart page is displayed with items", "main.2.then.1");
      } }
    }, "Verify: The cart page is displayed with items", 'main.2.then.1', '0e8e8201-51ca-46d9-8b55-6dca37c0221a', false);
  } else {
    // main.2.else.0: Verify: This branch should not execute
    page = agent.agentServices.validatePage(page);
    await agent.assert(page, "Verify: This branch should not execute", "main.2.else.0");
  }

  // main.3: Conditional check
  if ( page.url().includes('/cart')) {
    // Step: Proceed to checkout
    // main.3.then.0.0: Click the Checkout button
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      await page.getByRole('button', { name: 'Checkout' }).click()
    }, "Click the Checkout button", 'main.3.then.0.0', '4156074b-b085-409f-8e49-ba0953add861', true);

    // main.3.then.0.1: Verify: The checkout information page is displayed
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      { const _t = Date.now(); try {
        await expect(page.getByText('Checkout: Your Information')).toBeVisible({ timeout: 2000 })
        console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The checkout information page is displayed"`);
      } catch (_e) {
        console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The checkout information page is displayed"`);
        await agent.assert(page, "The checkout information page is displayed", "main.3.then.0.1");
      } }
    }, "Verify: The checkout information page is displayed", 'main.3.then.0.1', '668663a2-9b61-4bea-b401-e2fa3d2c3618', false);

    // main.3.then.0.2: Click the Cancel button
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      await page.getByRole('button', { name: 'Cancel' }).click()
    }, "Click the Cancel button", 'main.3.then.0.2', '715cf420-1527-40b9-9a33-fa9314ddd22a', true);

    // main.3.then.0.3: Verify: The cart page is displayed
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      { const _t = Date.now(); try {
        await expect(page.getByText('Your Cart')).toBeVisible({ timeout: 2000 })
        console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The cart page is displayed"`);
      } catch (_e) {
        console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The cart page is displayed"`);
        await agent.assert(page, "The cart page is displayed", "main.3.then.0.3");
      } }
    }, "Verify: The cart page is displayed", 'main.3.then.0.3', '04e4581a-2d44-4951-998c-ee6bad9bbcc3', false);
  }

  // main.4: Navigate to /inventory.html
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("go_to_url", page, {
      action_data: { kwargs: { url: "/inventory.html" } },
    });
  }, "Navigate to /inventory.html", 'main.4', 'a1bfa907-5eea-4133-a075-b318d682bb1e', true);

  // main.5: Remove Sauce Labs Backpack from cart
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.locator('[data-test="remove-sauce-labs-backpack"]').first().click({ timeout: 5000 });
  }, "Remove Sauce Labs Backpack from cart", 'main.5', '2e25fd0f-770e-4697-9c3c-ada99e66a2cf', true);

  // main.6: Loop
  const loop_main_6_start = Date.now();
  const loop_main_6_timeout = 30000;
  const loop_main_6_check = () => {
    if (Date.now() - loop_main_6_start > loop_main_6_timeout) {
      throw new Error('While loop exceeded timeout of 30s');
    }
    return true;
  };
  while (loop_main_6_check() && ( (await page.locator('button:has-text("Add to cart")').count()) > 0)) {
    // main.6.body.0: Click the first Add to cart button
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      await page.locator('button:has-text("Add to cart")').first().click()
    }, "Click the first Add to cart button", 'main.6.body.0', 'e52dac3c-b5f2-4d1c-aeb3-e58178b1805f', true);
  }

  // main.7: Verify: All 6 products are in the cart
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.locator('[data-test="shopping-cart-badge"]')).toHaveText('6', { timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "All 6 products are in the cart"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "All 6 products are in the cart"`);
      await agent.assert(page, "All 6 products are in the cart", "main.7");
    } }
  }, "Verify: All 6 products are in the cart", 'main.7', 'a3f7c8ba-63b4-4efd-8741-30dbd5e2e958', false);
});