// @generated by shiplightai v0.1.28
import { test, expect } from 'shiplightai/fixture';

test.use({
  "viewport": {
    "width": 375,
    "height": 812
  },
  "locale": "en-US"
});

test('@smoke @mobile Mobile inventory browsing', async ({ page, agent }) => {
  // Test steps
  // main.0: Navigate to /inventory.html
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("go_to_url", page, {
      action_data: { kwargs: { url: "/inventory.html" } },
    });
  }, "Navigate to /inventory.html", 'main.0', '06aa5f2c-32cf-4cb0-b58f-479b49c66186', true);

  // main.1: Verify: The inventory page is displayed
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.getByText('Products')).toBeVisible({ timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The inventory page is displayed"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The inventory page is displayed"`);
      await agent.assert(page, "The inventory page is displayed", "main.1");
    } }
  }, "Verify: The inventory page is displayed", 'main.1', '5d3c4932-a0a5-47ca-a042-4381fd8db050', false);

  // main.2: Verify: The product listings are visible on the page
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.locator('.inventory_item').first()).toBeVisible({ timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The product listings are visible on the page"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The product listings are visible on the page"`);
      await agent.assert(page, "The product listings are visible on the page", "main.2");
    } }
  }, "Verify: The product listings are visible on the page", 'main.2', '8618d993-0dfe-4a16-acdb-e3e218f7275c', false);

  // main.3: Add Sauce Labs Backpack to cart
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.getByRole('button', { name: 'Add to cart' }).first().click()
  }, "Add Sauce Labs Backpack to cart", 'main.3', '80f25a06-fc3e-4b17-8c9f-15e5fb7b5843', true);

  // main.4: Click the shopping cart icon
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.locator('[data-test="shopping-cart-link"]').click()
  }, "Click the shopping cart icon", 'main.4', '489351ad-ab83-4fd1-9260-f828df43c60d', true);

  // main.5: Verify: The cart contains the selected product
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.locator('.cart_item')).toHaveCount(1, { timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The cart contains the selected product"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The cart contains the selected product"`);
      await agent.assert(page, "The cart contains the selected product", "main.5");
    } }
  }, "Verify: The cart contains the selected product", 'main.5', '9f9cae95-195f-4fb3-b766-4611d050e8b2', false);
});