// @generated by shiplightai v0.1.28
import { test, expect } from 'shiplightai/fixture';

test('Use variables to fill checkout information', async ({ page, agent }) => {
  // Test steps
  // main.0: Navigate to /inventory.html
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("go_to_url", page, {
      action_data: { kwargs: { url: "/inventory.html" } },
    });
  }, "Navigate to /inventory.html", 'main.0', '73e1a4ee-f8fe-40c3-954a-cd312fa1f1d5', true);

  // main.1: Add Sauce Labs Backpack to cart
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.getByRole('button', { name: 'Add to cart' }).first().click()
  }, "Add Sauce Labs Backpack to cart", 'main.1', '216accea-0a04-4b83-b9a3-9f65969c94dd', true);

  // main.2: Click the shopping cart icon
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.locator('[data-test="shopping-cart-link"]').click()
  }, "Click the shopping cart icon", 'main.2', '292aee88-3084-49b9-a9b5-53f56e9cf6a7', true);

  // main.3: Click the Checkout button
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.getByRole('button', { name: 'Checkout' }).click()
  }, "Click the Checkout button", 'main.3', 'c507e1e6-b510-41cd-89c9-0e545205af9b', true);

  // main.4: Enter first name from variable
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("input_text", page, {
      action_data: { kwargs: { text: "{{SAUCE_USER}}" } },
      locator: "getByPlaceholder('First Name')",
    });
  }, "Enter first name from variable", 'main.4', '97f69ea1-5f7c-4957-8b58-870fc0c68028', true);

  // main.5: Enter last name
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("input_text", page, {
      action_data: { kwargs: { text: "Tester" } },
      locator: "getByPlaceholder('Last Name')",
    });
  }, "Enter last name", 'main.5', 'c7d83dcc-da36-412c-bab5-4afc86b0c9eb', true);

  // main.6: Enter zip code
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("input_text", page, {
      action_data: { kwargs: { text: "12345" } },
      locator: "getByPlaceholder('Zip/Postal Code')",
    });
  }, "Enter zip code", 'main.6', '14a09210-b6d9-47a4-8cf3-664d2ed0a059', true);

  // main.7: Click Continue
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.getByRole('button', { name: 'Continue' }).click()
  }, "Click Continue", 'main.7', '18124627-57d5-431a-aa8e-8add3ce51187', true);

  // main.8: Verify: The checkout overview page is displayed
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.getByText('Checkout: Overview')).toBeVisible({ timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The checkout overview page is displayed"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The checkout overview page is displayed"`);
      await agent.assert(page, "The checkout overview page is displayed", "main.8");
    } }
  }, "Verify: The checkout overview page is displayed", 'main.8', '7bf13f60-ea00-4627-b435-9d358f5fe1e5', false);
});