// @generated by shiplightai v0.1.28
import { test, expect } from 'shiplightai/fixture';

test('Navigate through the site and clean up with teardown', async ({ page, agent }) => {
  try {
    // Test steps
    // main.0: Navigate to /inventory.html
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      await agent.execAction("go_to_url", page, {
        action_data: { kwargs: { url: "/inventory.html" } },
      });
    }, "Navigate to /inventory.html", 'main.0', 'fcd9956e-2200-426a-9733-31056b427c5f', true);

    // main.1: Save the inventory URL
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      await agent.execAction("save_variable", page, {
        action_data: { kwargs: { name: "inventory_url", value: "js: page.url()" } },
      });
    }, "Save the inventory URL", 'main.1', '5a9130bf-eb2d-4eb7-a2a3-1430a07ddc7e', true);

    // main.2: Click the first product name
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      await page.locator('.inventory_item_name').first().click()
    }, "Click the first product name", 'main.2', '33ab549f-c046-4c66-8ef7-7c96c19a3d19', true);

    // main.3: Verify: The product detail page is displayed
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      { const _t = Date.now(); try {
        await expect(page.locator('.inventory_details_name')).toBeVisible({ timeout: 2000 })
        console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The product detail page is displayed"`);
      } catch (_e) {
        console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The product detail page is displayed"`);
        await agent.assert(page, "The product detail page is displayed", "main.3");
      } }
    }, "Verify: The product detail page is displayed", 'main.3', '5e042962-b46a-4b54-8b2b-9e3148b69e88', false);

    // main.4: Go back to inventory
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      await agent.execAction("go_back", page, {});
    }, "Go back to inventory", 'main.4', '0b0d8cda-7f78-4d05-b98b-1080092964c1', true);

    // main.5: Verify: The inventory page is displayed
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      { const _t = Date.now(); try {
        await expect(page.getByText('Products')).toBeVisible({ timeout: 2000 })
        console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The inventory page is displayed"`);
      } catch (_e) {
        console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The inventory page is displayed"`);
        await agent.assert(page, "The inventory page is displayed", "main.5");
      } }
    }, "Verify: The inventory page is displayed", 'main.5', '09fd6f42-7e9b-4632-ad85-db3a24bd9a64', false);

    // main.6: Navigate to /cart.html
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      await agent.execAction("go_to_url", page, {
        action_data: { kwargs: { url: "/cart.html" } },
      });
    }, "Navigate to /cart.html", 'main.6', 'd79351af-5ea5-40df-8987-b21b3f659af6', true);

    // main.7: Verify: The cart page is displayed
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      { const _t = Date.now(); try {
        await expect(page.getByText('Your Cart')).toBeVisible({ timeout: 2000 })
        console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The cart page is displayed"`);
      } catch (_e) {
        console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The cart page is displayed"`);
        await agent.assert(page, "The cart page is displayed", "main.7");
      } }
    }, "Verify: The cart page is displayed", 'main.7', '3c648459-a80d-40a5-94e6-19b068ce37a9', false);

    // main.8: Reload the page
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      await page.reload({ waitUntil: 'domcontentloaded' })
    }, "Reload the page", 'main.8', '39a37eef-27b9-459f-92d9-8f677ea056d8', true);

    // main.9: Verify: The cart page is still displayed after reload
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      { const _t = Date.now(); try {
        await expect(page.getByText('Your Cart')).toBeVisible({ timeout: 2000 })
        console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The cart page is still displayed after reload"`);
      } catch (_e) {
        console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The cart page is still displayed after reload"`);
        await agent.assert(page, "The cart page is still displayed after reload", "main.9");
      } }
    }, "Verify: The cart page is still displayed after reload", 'main.9', '0c6f80de-76ab-4680-a4ca-e59228da1781', false);

    // main.10: Verify: The current page URL is different from the saved inventory_url
    page = agent.agentServices.validatePage(page);
    await agent.assert(page, "Verify: The current page URL is different from the saved inventory_url", "main.10");
  } finally {
    // Teardown
    // teardown.0: Open the sidebar menu
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      await page.getByRole('button', { name: 'Open Menu' }).click()
    }, "Open the sidebar menu", 'teardown.0', '9b753d7f-9f34-497a-ad50-64d8177aa2d9', true);

    // teardown.1: Click Reset App State
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      await page.getByText('Reset App State').click()
    }, "Click Reset App State", 'teardown.1', '47dd2dfe-1672-4e20-8d7f-3dab74b26e71', true);
  }
});