// @generated by shiplightai v0.1.28
import { test, expect } from 'shiplightai/fixture';

test('Verify authenticated user can access inventory directly', async ({ page, agent }) => {
  // Test steps
  // main.0: Navigate to /inventory.html
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("go_to_url", page, {
      action_data: { kwargs: { url: "/inventory.html" } },
    });
  }, "Navigate to /inventory.html", 'main.0', 'f4f8a7cf-dc3c-42d6-8713-f28006fe0bd2', true);

  // main.1: Verify: The inventory page is displayed without needing to log in
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.getByText('Products')).toBeVisible({ timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The inventory page is displayed without needing to log in"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The inventory page is displayed without needing to log in"`);
      await agent.assert(page, "The inventory page is displayed without needing to log in", "main.1");
    } }
  }, "Verify: The inventory page is displayed without needing to log in", 'main.1', '41a20a1b-c43b-4111-8efc-5b9c5859c012', false);

  // main.2: Add Sauce Labs Backpack to cart
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.getByRole('button', { name: 'Add to cart' }).first().click()
  }, "Add Sauce Labs Backpack to cart", 'main.2', '8875ce43-82ae-44aa-adf2-7386bff01180', true);

  // main.3: Click the shopping cart icon
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.locator('[data-test="shopping-cart-link"]').click()
  }, "Click the shopping cart icon", 'main.3', '077933bb-fc0b-4d5c-a9a7-29dd0c78a9f1', true);

  // main.4: Verify: The cart contains the selected product
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.locator('.cart_item')).toHaveCount(1, { timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The cart contains the selected product"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The cart contains the selected product"`);
      await agent.assert(page, "The cart contains the selected product", "main.4");
    } }
  }, "Verify: The cart contains the selected product", 'main.4', '58500a0a-a961-4cf5-b638-a3b1063c9450', false);
});