// @generated by shiplightai v0.1.28
import { test, expect } from 'shiplightai/fixture';

test('Complete checkout using a reusable template', async ({ page, agent }) => {
  // Test steps
  // main.0: Navigate to /inventory.html
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("go_to_url", page, {
      action_data: { kwargs: { url: "/inventory.html" } },
    });
  }, "Navigate to /inventory.html", 'main.0', '48651d37-31ed-4689-ae94-a5a8031906cf', true);

  // main.1: Add Sauce Labs Backpack to cart
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.getByRole('button', { name: 'Add to cart' }).first().click()
  }, "Add Sauce Labs Backpack to cart", 'main.1', 'afe7c553-4d28-4778-872c-9c70cbd4547d', true);

  // main.2: Click the shopping cart icon
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.locator('[data-test="shopping-cart-link"]').click()
  }, "Click the shopping cart icon", 'main.2', '2b85f6fe-99ab-4bec-99da-0c37d7c6b19f', true);

  // main.3: Click the Checkout button
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.getByRole('button', { name: 'Checkout' }).click()
  }, "Click the Checkout button", 'main.3', 'e244cb7a-ef09-4159-9374-bb94c63361f0', true);

  // main.4: Enter first name
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("input_text", page, {
      action_data: { kwargs: { text: "Test" } },
      locator: "getByPlaceholder('First Name')",
    });
  }, "Enter first name", 'main.4', 'f4747ea6-38f7-45cc-a734-a19f3f1382a5', true);

  // main.5: Enter last name
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("input_text", page, {
      action_data: { kwargs: { text: "User" } },
      locator: "getByPlaceholder('Last Name')",
    });
  }, "Enter last name", 'main.5', 'e30753db-efed-46a1-841a-683bad0ca485', true);

  // main.6: Enter zip code
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("input_text", page, {
      action_data: { kwargs: { text: 90210 } },
      locator: "getByPlaceholder('Zip/Postal Code')",
    });
  }, "Enter zip code", 'main.6', '966856a2-dd44-4a1e-af6d-03652ecfbc42', true);

  // main.7: Click Continue
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.getByRole('button', { name: 'Continue' }).click()
  }, "Click Continue", 'main.7', '28c03f62-8ee6-4762-989f-c10242f6aea0', true);

  // main.8: Verify: The checkout overview page is displayed
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.getByText('Checkout: Overview')).toBeVisible({ timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The checkout overview page is displayed"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The checkout overview page is displayed"`);
      await agent.assert(page, "The checkout overview page is displayed", "main.8");
    } }
  }, "Verify: The checkout overview page is displayed", 'main.8', 'b0a0ad75-4bc4-4db7-864e-74ae1b9a065f', false);

  // main.9: Click the Finish button
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.getByRole('button', { name: 'Finish' }).click()
  }, "Click the Finish button", 'main.9', 'ed4ba328-4742-43e5-825d-9036aa79983a', true);

  // main.10: Verify: The order confirmation page is displayed
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.getByText('Thank you for your order')).toBeVisible({ timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The order confirmation page is displayed"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The order confirmation page is displayed"`);
      await agent.assert(page, "The order confirmation page is displayed", "main.10");
    } }
  }, "Verify: The order confirmation page is displayed", 'main.10', '05d65a01-f1f5-4924-89b6-e06edf6b02bc', false);
});