// @generated by shiplightai v0.1.28
import { test, expect } from 'shiplightai/fixture';
import { get_cart_count } from '../helpers/cart';
import { verify_cart_count } from '../helpers/cart';
import { clear_cart } from '../helpers/cart';

test('Use custom functions to manage and verify the cart', async ({ page, agent }) => {
  // Test steps
  // main.0: Navigate to /inventory.html
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("go_to_url", page, {
      action_data: { kwargs: { url: "/inventory.html" } },
    });
  }, "Navigate to /inventory.html", 'main.0', '5dceb33f-de7d-48bc-b20f-45f27f206049', true);

  // main.1: Add Sauce Labs Backpack to cart
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.locator('[data-test="add-to-cart-sauce-labs-backpack"]').click()
  }, "Add Sauce Labs Backpack to cart", 'main.1', '9c3b5259-56bd-4c89-b62c-d2c0741a9ad9', true);

  // main.2: Add Sauce Labs Bike Light to cart
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.locator('[data-test="add-to-cart-sauce-labs-bike-light"]').click()
  }, "Add Sauce Labs Bike Light to cart", 'main.2', '0ba8cbd0-a57e-4c69-ac6f-2bee75badecd', true);

  // main.3: Check the cart count with a custom function
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await get_cart_count(page);
  }, "Check the cart count with a custom function", 'main.3', '9a07327c-6922-49d8-8d50-9f82086a4984', false);

  // main.4: Verify cart has 2 items
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await verify_cart_count(page, 2, "Expected 2 items after adding backpack and bike light");
  }, "Verify cart has 2 items", 'main.4', '95a22c08-b091-42ad-9068-45e9011b0edf', false);

  // main.5: Clear the cart using a custom function
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await clear_cart(page);
  }, "Clear the cart using a custom function", 'main.5', '811db05b-f2c3-4ca3-812c-fcb299123671', false);

  // main.6: Click the shopping cart icon
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.locator('[data-test="shopping-cart-link"]').click()
  }, "Click the shopping cart icon", 'main.6', 'dbae158a-2c9f-4c9a-93bc-dd64e63d37b9', true);

  // main.7: Verify: The cart is empty
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.locator('.cart_item')).toHaveCount(0, { timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The cart is empty"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The cart is empty"`);
      await agent.assert(page, "The cart is empty", "main.7");
    } }
  }, "Verify: The cart is empty", 'main.7', 'c0d26f71-6376-4688-bf65-3abbc780a4bb', false);
});