// @generated by shiplightai v0.1.28
import { test, expect } from 'shiplightai/fixture';

test.describe.serial('@smoke @suite Inventory Browsing Suite', () => {
  test.beforeEach(async ({ page, agent }) => {
    // beforeEach.0: Navigate to /inventory.html
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      await agent.execAction("go_to_url", page, {
        action_data: { kwargs: { url: "/inventory.html" } },
      });
    }, "Navigate to /inventory.html", 'beforeEach.0', 'e5858713-351c-4a1c-a3fc-9d42728fe417', true);
  });

  test('Sort products by price', async ({ page, agent }) => {
    // Test steps
    // main.0: Sort by price low to high
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      await agent.execAction("select_dropdown_option", page, {
        action_data: { kwargs: { text: "Price (low to high)" } },
        locator: "getByRole('combobox')",
      });
    }, "Sort by price low to high", 'main.0', 'fb94dc04-7c0b-4f82-90b8-83ab7bf06f82', true);

    // main.1: Verify: Products are sorted by price ascending
    page = agent.agentServices.validatePage(page);
    await agent.assert(page, "Verify: Products are sorted by price ascending", "main.1");
  });

  test('View product details', async ({ page, agent }) => {
    // Test steps
    // main.0: Click the first product name
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      await page.locator('.inventory_item_name').first().click()
    }, "Click the first product name", 'main.0', '94b0daea-9064-4840-9cd5-84db7f4a7e55', true);

    // main.1: Verify: The product detail page is displayed
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      { const _t = Date.now(); try {
        await expect(page.locator('.inventory_details_name')).toBeVisible({ timeout: 2000 })
        console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The product detail page is displayed"`);
      } catch (_e) {
        console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The product detail page is displayed"`);
        await agent.assert(page, "The product detail page is displayed", "main.1");
      } }
    }, "Verify: The product detail page is displayed", 'main.1', 'bbe8792e-f773-4b6d-9b93-2b82631dde2f', false);
  });

  test('Add product to cart', async ({ page, agent }) => {
    try {
      // Test steps
      // main.0: Click Add to cart on Sauce Labs Backpack
      page = agent.agentServices.validatePage(page);
      await agent.step(page, async () => {
        await page.locator('[data-test="add-to-cart-sauce-labs-backpack"]').first().click({ timeout: 5000 });
      }, "Click Add to cart on Sauce Labs Backpack", 'main.0', '121d9832-c73c-4b66-860f-b6175bd5685b', true);

      // main.1: Verify: Cart badge shows 1 item
      page = agent.agentServices.validatePage(page);
      await agent.assert(page, "Verify: Cart badge shows 1 item", "main.1");
    } finally {
      // Teardown
      // teardown.0: Remove Sauce Labs Backpack from cart
      page = agent.agentServices.validatePage(page);
      await agent.step(page, async () => {
        await page.locator('[data-test="remove-sauce-labs-backpack"]').first().click({ timeout: 5000 });
      }, "Remove Sauce Labs Backpack from cart", 'teardown.0', '8c269e39-1fa1-4edc-bbcb-672dc22a96d0', true);
    }
  });
});