// @generated by shiplightai v0.1.28
import { test, expect } from 'shiplightai/fixture';

test.describe.serial('@e2e @hooks Cart Management Suite', () => {
  test.beforeAll(async ({ browser }, workerInfo) => {
    const page = await browser.newPage({ baseURL: workerInfo.project.use.baseURL });
    // beforeAll.0: Navigate to /inventory.html
    await page.goto("/inventory.html", { waitUntil: 'domcontentloaded' });
    await page.close();
  });

  test.beforeEach(async ({ page, agent }) => {
    // beforeEach.0: Navigate to /inventory.html
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      await agent.execAction("go_to_url", page, {
        action_data: { kwargs: { url: "/inventory.html" } },
      });
    }, "Navigate to /inventory.html", 'beforeEach.0', '154bd64d-3855-4f91-9f6b-37bc49724aa5', true);

    // beforeEach.1: Add Sauce Labs Backpack to cart
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      await page.locator('[data-test="add-to-cart-sauce-labs-backpack"]').first().click({ timeout: 5000 });
    }, "Add Sauce Labs Backpack to cart", 'beforeEach.1', 'c3adab3a-10ce-4ce8-87e0-c908056137bc', true);
  });

  test('Verify cart badge shows item count', async ({ page, agent }) => {
    // Test steps
    // main.0: Verify: The shopping cart badge shows 1 item
    page = agent.agentServices.validatePage(page);
    await agent.assert(page, "Verify: The shopping cart badge shows 1 item", "main.0");
  });

  test('Verify remove button appears after adding to cart', async ({ page, agent }) => {
    // Test steps
    // main.0: Verify: A Remove button is visible for Sauce Labs Backpack
    page = agent.agentServices.validatePage(page);
    await agent.assert(page, "Verify: A Remove button is visible for Sauce Labs Backpack", "main.0");
  });

  test.afterEach(async ({ page, agent }) => {
    // afterEach.0: Remove Backpack from cart if present
    page = agent.agentServices.validatePage(page);
    await agent.step(page, async () => {
      await page.locator('[data-test="remove-sauce-labs-backpack"]').first().click({ timeout: 5000 });
    }, "Remove Backpack from cart if present", 'afterEach.0', 'd1eab7df-2995-401c-8566-97bb0b6ec4b6', true);
  });

  test.afterAll(async ({ browser }, workerInfo) => {
    const page = await browser.newPage({ baseURL: workerInfo.project.use.baseURL });
    // afterAll.0: Navigate to /inventory.html
    await page.goto("/inventory.html", { waitUntil: 'domcontentloaded' });
    await page.close();
  });
});