// @generated by shiplightai v0.1.28
import { test, expect } from 'shiplightai/fixture';

test('@e2e @parameterized Add product to cart [backpack]', async ({ page, agent }) => {
  // Test steps
  // main.0: Navigate to /inventory.html
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("go_to_url", page, {
      action_data: { kwargs: { url: "/inventory.html" } },
    });
  }, "Navigate to /inventory.html", 'main.0', 'f96f3989-77b3-483c-aee0-2c1c9ebd4bf4', true);

  // main.1: Add product to cart
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.locator('[data-test="add-to-cart-sauce-labs-backpack"]').first().click({ timeout: 5000 });
  }, "Add product to cart", 'main.1', 'e9f7676d-0128-4784-b002-31067d655cf7', true);

  // main.2: Click cart icon
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.locator('[data-test="shopping-cart-link"]').first().click({ timeout: 5000 });
  }, "Click cart icon", 'main.2', 'cb92a716-f09e-47f5-83ab-1ae10392a577', true);

  // main.3: Verify: Sauce Labs Backpack is in the cart
  page = agent.agentServices.validatePage(page);
  await agent.assert(page, "Verify: Sauce Labs Backpack is in the cart", "main.3");
});

test('@e2e @parameterized Add product to cart [bike light]', async ({ page, agent }) => {
  // Test steps
  // main.0: Navigate to /inventory.html
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("go_to_url", page, {
      action_data: { kwargs: { url: "/inventory.html" } },
    });
  }, "Navigate to /inventory.html", 'main.0', 'c9ad4c63-13f1-4474-9967-eedc0ef96083', true);

  // main.1: Add product to cart
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.locator('[data-test="add-to-cart-sauce-labs-bike-light"]').first().click({ timeout: 5000 });
  }, "Add product to cart", 'main.1', '377b4aec-82e9-48dc-a189-907ef8796502', true);

  // main.2: Click cart icon
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.locator('[data-test="shopping-cart-link"]').first().click({ timeout: 5000 });
  }, "Click cart icon", 'main.2', '5c29a76a-84d9-487f-81e3-5089fb6f6cf1', true);

  // main.3: Verify: Sauce Labs Bike Light is in the cart
  page = agent.agentServices.validatePage(page);
  await agent.assert(page, "Verify: Sauce Labs Bike Light is in the cart", "main.3");
});
