// @generated by shiplightai v0.1.28
import { test, expect } from 'shiplightai/fixture';

test('Verify page renders correctly with mocked data and localStorage', async ({ page, agent }) => {
  // Test steps
  // main.0: Navigate to /inventory.html
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("go_to_url", page, {
      action_data: { kwargs: { url: "/inventory.html" } },
    });
  }, "Navigate to /inventory.html", 'main.0', 'a785c3ec-a0ac-480c-ba0d-d394625bbd77', true);

  // main.1: Code block
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    {
      await page.route('**/api/users', (route) => route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify([
          { id: 1, name: 'Alice', role: 'Admin' },
          { id: 2, name: 'Bob', role: 'Editor' },
        ]),
      }));
      
    }
  }, "Code block", 'main.1', '544c5b37-3be1-4d86-9641-10bc6260facb', false);

  // main.2: Code block
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    {
      await page.evaluate(() => localStorage.setItem('feature_beta', 'true'))
    }
  }, "Code block", 'main.2', 'b59bdf05-0706-4063-93f2-760d15d46c08', false);

  // main.3: Navigate to /inventory.html
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("go_to_url", page, {
      action_data: { kwargs: { url: "/inventory.html" } },
    });
  }, "Navigate to /inventory.html", 'main.3', 'e566ffbb-8b72-4c0c-864c-faef6043e221', true);

  // main.4: Verify: The inventory page is displayed
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.getByText('Products')).toBeVisible({ timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The inventory page is displayed"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The inventory page is displayed"`);
      await agent.assert(page, "The inventory page is displayed", "main.4");
    } }
  }, "Verify: The inventory page is displayed", 'main.4', 'd41beaaf-d873-4e6c-a3c6-2afb1a69ca62', false);

  // main.5: Code block
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    {
      const title = await page.title();
      expect(title).toContain('Swag Labs');
      
    }
  }, "Code block", 'main.5', 'cf35c4a9-281c-4ee7-af51-509fb8324ec1', false);
});