// @generated by shiplightai v0.1.28
import { test, expect } from 'shiplightai/fixture';

test('Verify inventory page with JS code cache', async ({ page, agent }) => {
  // Test steps
  // main.0: Navigate to /inventory.html
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("go_to_url", page, {
      action_data: { kwargs: { url: "/inventory.html" } },
    });
  }, "Navigate to /inventory.html", 'main.0', '146b75e3-940e-4c8b-aecc-5760f325e11c', true);

  // main.1: Verify: The page has a heading
  page = agent.agentServices.validatePage(page);
  await agent.assert(page, "Verify: The page has a heading", "main.1");

  // main.2: Verify: The Products heading is visible
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.getByText('Products')).toBeVisible({ timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The Products heading is visible"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The Products heading is visible"`);
      await agent.assert(page, "The Products heading is visible", "main.2");
    } }
  }, "Verify: The Products heading is visible", 'main.2', '39722c7f-aeea-442d-822c-af4bdaec99ad', false);

  // main.3: Verify: There are 6 inventory items
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.locator('.inventory_item')).toHaveCount(6, { timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "There are 6 inventory items"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "There are 6 inventory items"`);
      await agent.assert(page, "There are 6 inventory items", "main.3");
    } }
  }, "Verify: There are 6 inventory items", 'main.3', '412c71ed-dec1-46a2-a33c-ea2beb1e29a7', false);

  // main.4: Add Sauce Labs Backpack to cart
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await page.locator('[data-test="add-to-cart-sauce-labs-backpack"]').click()
  }, "Add Sauce Labs Backpack to cart", 'main.4', 'f929b8cc-9734-421d-8d71-49090c2a093e', true);

  // main.5: Verify: The shopping cart badge shows 1
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.locator('[data-test="shopping-cart-badge"]')).toHaveText('1', { timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The shopping cart badge shows 1"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The shopping cart badge shows 1"`);
      await agent.assert(page, "The shopping cart badge shows 1", "main.5");
    } }
  }, "Verify: The shopping cart badge shows 1", 'main.5', 'fd9fd420-d2ea-4202-ab1f-59878dd4285b', false);
});