// @generated by shiplightai v0.1.28
import { test, expect } from 'shiplightai/fixture';

test.use({
  "account": {
    "username": "problem_user",
    "password": "secret_sauce",
    "auth_login": "./demo/auth.login.ts"
  }
});

test('Verify problem_user can access inventory', async ({ page, agent }) => {
  // Test steps
  // main.0: Navigate to /inventory.html
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    await agent.execAction("go_to_url", page, {
      action_data: { kwargs: { url: "/inventory.html" } },
    });
  }, "Navigate to /inventory.html", 'main.0', 'f2b655b8-a445-41d9-9eba-9e1fcc953ad5', true);

  // main.1: Verify: The inventory page shows products
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.getByText('Products')).toBeVisible({ timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "The inventory page shows products"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "The inventory page shows products"`);
      await agent.assert(page, "The inventory page shows products", "main.1");
    } }
  }, "Verify: The inventory page shows products", 'main.1', '0b3c8449-dfc0-43e5-9f86-91693ee66ef1', false);

  // main.2: Verify: There are 6 products listed on the page
  page = agent.agentServices.validatePage(page);
  await agent.step(page, async () => {
    { const _t = Date.now(); try {
      await expect(page.locator('.inventory_item')).toHaveCount(6, { timeout: 2000 })
      console.log(`[VERIFY:JS] ✓ ${((Date.now()-_t)/1000).toFixed(1)}s: "There are 6 products listed on the page"`);
    } catch (_e) {
      console.log(`[VERIFY:JS→AI] JS failed ${((Date.now()-_t)/1000).toFixed(1)}s: (${_e instanceof Error ? _e.message : String(_e)}), falling back to AI: "There are 6 products listed on the page"`);
      await agent.assert(page, "There are 6 products listed on the page", "main.2");
    } }
  }, "Verify: There are 6 products listed on the page", 'main.2', '792e736c-d237-4a68-92e2-ca95f698f395', false);
});